sudo: required
language: node_js
node_js:
  - '8'
  - 'stable'
cache:
  directories:
    - node_modules
before_script:
  - export CHROME_PATH="$(which google-chrome-stable)"
script:
  - npm run test:lint
  - npm run test:examples -- --ci
addons:
  chrome: stable
